---
title: "QNX QEMU Setup"
date: 2025-12-15T22:01:01+01:00
draft: true
description: "QNX has recently shared their 8.0 version with a free license for learning and academic projects, opening their real-time OS to many new potential users. Not everyone has a physical device to run the QNX, for those QNX has prepared a QEMU wrapper - `mkqnximage` command."
---

QNX has recently shared their 8.0 version with a free license for learning and academic projects, opening their real-time OS to many new potential users. 
Not everyone has a physical device to run the QNX, for those QNX has prepared a QEMU wrapper - `mkqnximage` command.

== Prerequisites

This article assumes that the https://qnx.software/en/software/products-and-solutions/qnx-software-development-platform[QNX SDP 8.0] is already available at your local machine 
with access to the `mkqnximage` command. If not, then take my hint - remember to apply for the license and then **deploy** it specifically to your own email address 
through https://www.qnx.com/account/dashboard/[my QNX Lincense Manager]. I had plently of problems with getting access to the QNX SDP simply because my license was not deployed to my account.

== mkqnximage

In my understanding `mkqnximage` is a wrapper script genreating a QNX OS virtual machine image. It doesn't just wrap on QEMU, other supervisors, _VMWare_ and _VirtualBox_, are supported as well.
The command is described with quite a detail in the https://www.qnx.com/developers/docs/8.0/com.qnx.doc.neutrino.utilities/topic/m/mkqnximage.html[documentation], however a few important caveats are never mentioned. I'll show you around.

=== Basic usage

First, to get access to the `mkqnximage` command, source the QNX SDP environment with the __qnxsdp-env.sh__ script:
----
$ source ~/qnx/qnx800/qnxsdp-env.sh 
QNX_HOST=/home/antoni/qnx/qnx800/host/linux/x86_64
QNX_TARGET=/home/antoni/qnx/qnx800/target/qnx
MAKEFLAGS=-I/home/antoni/qnx/qnx800/target/qnx/usr/include
----

Let's get familiar with the `--help` option as it covers a lot more details than the official documentation. `--help` output describes `--data-size`,
`--data-inodes` and `--ram` options which make the created image even more flexible.

----
$ mkqnximage --help
----

Now, create a directory that will store the environment (virtual disks and option files) created by `mkqnximage`. My choice of the dir name is just _qnximage_, enter the directory:

----
mkdir qnximage
cd qnximage
----

Finally, to create an environment with all of the options set default, simply run `mkqnximage` with no parameters. 
This will create an x86_64 QEMU emulation. Then, to launch it, use a `--run` parameter.

----
mkqnximage
mkqnximage --run
----

=== Exiting and restarting the emulation

Once in the emulator's console (assuming it's QEMU), there's a simple way out. Just hit `Ctrl+A` and then `X`. Yeah, that's it - `Ctrl+A X`

`mkqnximage` uses persistent storage and all the changes done to the emulation are saved in the virutal disk. Thanks to this feature it's possible to restart
an emulation after it had exited. To do so, enter the directory where the emulation environment was created (for example the _qnximage_ directory from the previous step), then run `mkqnximage --run`.

=== arch or x86?



=== Not enough disk space?

=== Large disk spaces, but still too many files?

Sounds counterintuitive, right? 

=== Full command with all basic options

----
mkqnximage --type=qemu --hostname=qnxmachine --arch='aarch64le' --data-size='8192' --ram='4G' --data-inodes='10000000'
----

=== The IP Address and SSH password

The ip address can be fetched with `ifconfig` command from inside of the emulator console. The SSH server is enabled by default, 
and the password to it is the same as the requested user name. for example, the `root` user uses a password _root_.

== The end

Thanks for checking out my blog, feel free to ask me anything in the comments!
